//mod intro;
//mod variables;
//mod arrays_vectors;
//mod constants;
//mod tuples;
//mod expresions_advanced_let;
//mod traits_theme;
//mod simple_functions;
//mod functions_various_values;
//mod first_level_functions;
//mod generity;
//mod closures;
//mod conditionals_1;
//mod conditionals_2;
//mod match_coditional;
//mod loops;
//mod for_loop;
//mod structs_traits_1;
mod asociated_methods;

fn main() {
    //intro::run();
    //variables::run();
    //arrays_vectors::run();
    //constants::run();
    //tuples::run();
    //expresions_advanced_let::run();
    //traits_theme::run();
    //simple_functions::run();
    //functions_various_values::run();
    //first_level_functions::run();
    //generity::run();
    //closures::run();
    //conditionals_1::run();
    //conditionals_2::run();
    //match_coditional::run();
    //loops::run();
    //for_loop::run();
    //structs_traits_1::run();
    asociated_methods::run();
}
